name: d8-high-contrast
recipe: drupal8
config:
  webroot: web
  php: '7.3'
  database: mysql:5.7
  xdebug: false
tooling:
  drush:
    service: appserver
    cmd:
      - "drush --uri=http://d8-high-contrast.lndo.site"
